### ISSUE TITLE
Create Homepage

### ISSUE THREAD

**Issue by sn31** [sn31/cospedia-web#2]
- Come up with a catch phrase for Cospedia.
- Navbar & Footer
- Carousel with interesting statistics/infographics. Example: How often people use expired makeup products and the consequences; scientific studies about hygiene, etc.
- A description of Cospedia. 
- Link to the Appstore or an emulator.

Please post your findings here.

**Comment by hyewon92cho** [comment]
[Daily Mail - The dangers lurking inside makeup bags: Lab tests reveal how barely out-of-date cosmetics might be making you sick... with bacteria that could even cause meningitis ](http://www.dailymail.co.uk/femail/article-3209876/The-dangers-lurking-inside-makeup-bags-Lab-tests-reveal-barely-date-cosmetics-making-sick-bacteria-cause-meningitis.html)
According to a study conducted at London Metropolitan University, expired cosmetics contain unsafe levels of harmful bacteria.

**Comment by hyewon92cho** [comment]
Carousel Javascript Libraries
1. [Slick](http://kenwheeler.github.io/slick/) - I used this library for my website gallery page.
2. [Flickity](https://flickity.metafizzy.co/)
3. [Owl Carousel](https://owlcarousel2.github.io/OwlCarousel2/) - Jquery plugin carousel

**Comment by hyewon92cho** [comment]
[Canva](https://www.canva.com/) - An online tool for making infographics.

**Comment by hyewon92cho** [comment]
[FDA article about expiration date of cosmetic products](https://www.fda.gov/cosmetics/labeling/expirationdating/default.htm)

**Comment by hyewon92cho** [comment]
[Beauty Keeper](http://beautykeeperapp.com/) - an iOS app keeping track of cosmetic products' expiration dates
