### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by HyungNLee** [sn31/cospedia-web#4]
Ryan/Meria
  - Work on landing page, similar theme to Beauty Keeper App.
    * Modals for user sign-up/log-in
Hyewon/Skye
  - Work on user profile page.
    * Show user information in graphs.
    * Product expiration graph.
    * User functionality (Add/Delete/Edit products)
  - Work on connecting firebase database to website.

**Comment by sn31** [comment]
![alt text]: (https://i.imgur.com/yBag0Mp.png)
